config:
  backup: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  ubuntu-2gb-hel1-1:
    dotfiles:
    - f_tmux.conf
    - f_zshrc
    - f_starship.toml
  huawei:
    dotfiles:
    - d_nvim
